version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Puerto para conectarse a Redis

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - redis
